inherit_gem:
  rubocop-lts: config/rubygem_rspec.yml

require:
  - 'rubocop-minitest'
  - 'rubocop-sequel'

Sequel/SaveChanges:
  Enabled: false

Lint/UselessMethodDefinition:
  Enabled: false

RSpec/SpecFilePathFormat:
  Include:
    - spec
    - spec_orms

RSpec/BeforeAfterAll:
  Enabled: false
