name: Supported Compat Matrix

env:
  K_SOUP_COV_DO: false

on:
  push:
    branches:
      - 'main'
    tags:
      - '!*' # Do not execute on tags
  pull_request:
    branches:
      - '*'
  # Allow manually triggering the workflow.
  workflow_dispatch:

permissions:
  contents: read

# Cancels all previous workflow runs for the same branch that have not yet completed.
concurrency:
  # The concurrency group contains the workflow name and the branch name.
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  test:
    name: Specs - Ruby ${{ matrix.ruby }} ${{ matrix.appraisal }}${{ matrix.name_extra || '' }}
    if: "!contains(github.event.commits[0].message, '[ci skip]') && !contains(github.event.commits[0].message, '[skip ci]')"
    env: # $BUNDLE_GEMFILE must be set at job level, so it is set for all steps
      BUNDLE_GEMFILE: ${{ github.workspace }}/${{ matrix.gemfile }}.gemfile
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental || endsWith(matrix.ruby, 'head') }}
    strategy:
      matrix:
        include:
          # Ruby 3.1
          - ruby: "3.1"
            appraisal: "ar-7-0"
            taskname: "spec:orm:active_record"
            gemfile: "Appraisal.root"
            rubygems: latest
            bundler: latest
          - ruby: "3.1"
            appraisal: "ar-7-1"
            taskname: "spec:orm:active_record"
            gemfile: "Appraisal.root"
            rubygems: latest
            bundler: latest
          - ruby: "3.1"
            appraisal: "ar-7-2"
            taskname: "spec:orm:active_record"
            gemfile: "Appraisal.root"
            rubygems: latest
            bundler: latest
          - ruby: "3.1"
            appraisal: "couch-1.17"
            taskname: "spec:orm:couch_potato"
            gemfile: "Appraisal.root"
            rubygems: latest
            bundler: latest
          - ruby: "3.1"
            appraisal: "mongoid-8.1"
            taskname: "spec:orm:mongoid"
            gemfile: "Appraisal.root"
            rubygems: latest
            bundler: latest
          - ruby: "3.1"
            appraisal: "mongoid-9.0"
            taskname: "spec:orm:mongoid"
            gemfile: "Appraisal.root"
            rubygems: latest
            bundler: latest
          - ruby: "3.1"
            appraisal: "sequel-5.86"
            taskname: "spec:orm:sequel"
            gemfile: "Appraisal.root"
            rubygems: latest
            bundler: latest

          # Ruby 3.2
          - ruby: "3.2"
            appraisal: "ar-7-1"
            taskname: "spec:orm:active_record"
            gemfile: "Appraisal.root"
            rubygems: latest
            bundler: latest
          - ruby: "3.2"
            appraisal: "ar-7-2"
            taskname: "spec:orm:active_record"
            gemfile: "Appraisal.root"
            rubygems: latest
            bundler: latest
          - ruby: "3.2"
            appraisal: "ar-8-0"
            taskname: "spec:orm:active_record"
            gemfile: "Appraisal.root"
            rubygems: latest
            bundler: latest
          - ruby: "3.2"
            appraisal: "couch-1.17"
            taskname: "spec:orm:couch_potato"
            gemfile: "Appraisal.root"
            rubygems: latest
            bundler: latest
          - ruby: "3.2"
            appraisal: "mongoid-8.1"
            taskname: "spec:orm:mongoid"
            gemfile: "Appraisal.root"
            rubygems: latest
            bundler: latest
          - ruby: "3.2"
            appraisal: "mongoid-9.0"
            taskname: "spec:orm:mongoid"
            gemfile: "Appraisal.root"
            rubygems: latest
            bundler: latest
          - ruby: "3.2"
            appraisal: "sequel-5.86"
            taskname: "spec:orm:sequel"
            gemfile: "Appraisal.root"
            rubygems: latest
            bundler: latest

          # Ruby 3.3
          - ruby: "3.3"
            appraisal: "ar-7-2"
            taskname: "spec:orm:active_record"
            gemfile: "Appraisal.root"
            rubygems: latest
            bundler: latest
          - ruby: "3.3"
            appraisal: "ar-8-0"
            taskname: "spec:orm:active_record"
            gemfile: "Appraisal.root"
            rubygems: latest
            bundler: latest
          - ruby: "3.3"
            appraisal: "couch-1.17"
            taskname: "spec:orm:couch_potato"
            gemfile: "Appraisal.root"
            rubygems: latest
            bundler: latest
          - ruby: "3.3"
            appraisal: "mongoid-8.1"
            taskname: "spec:orm:mongoid"
            gemfile: "Appraisal.root"
            rubygems: latest
            bundler: latest
          - ruby: "3.3"
            appraisal: "mongoid-9.0"
            taskname: "spec:orm:mongoid"
            gemfile: "Appraisal.root"
            rubygems: latest
            bundler: latest
          - ruby: "3.3"
            appraisal: "sequel-5.86"
            taskname: "spec:orm:sequel"
            gemfile: "Appraisal.root"
            rubygems: latest
            bundler: latest

          # Ruby 3.4
          - ruby: "3.4"
            appraisal: "ar-7-2"
            taskname: "spec:orm:active_record"
            gemfile: "Appraisal.root"
            rubygems: latest
            bundler: latest
          - ruby: "3.4"
            appraisal: "ar-8-0"
            taskname: "spec:orm:active_record"
            gemfile: "Appraisal.root"
            rubygems: latest
            bundler: latest
          - ruby: "3.4"
            appraisal: "couch-1.17"
            taskname: "spec:orm:couch_potato"
            gemfile: "Appraisal.root"
            rubygems: latest
            bundler: latest
          - ruby: "3.4"
            appraisal: "mongoid-8.1"
            taskname: "spec:orm:mongoid"
            gemfile: "Appraisal.root"
            rubygems: latest
            bundler: latest
          - ruby: "3.4"
            appraisal: "mongoid-9.0"
            taskname: "spec:orm:mongoid"
            gemfile: "Appraisal.root"
            rubygems: latest
            bundler: latest
          - ruby: "3.4"
            appraisal: "sequel-5.86"
            taskname: "spec:orm:sequel"
            gemfile: "Appraisal.root"
            rubygems: latest
            bundler: latest

    steps:
      ### COUCHDB
      - name: Start CouchDB
        uses: iamssen/couchdb-github-action@master
        if: "endsWith(matrix.taskname, 'couch_potato')"
        with:
          couchdb-version: "3.4.1"
      - name: Smoke CouchDB
        if: "endsWith(matrix.taskname, 'couch_potato')"
        run: |
          curl -f http://127.0.0.1:5984/
          curl -X POST -H "Content-Type: application/json; charset=utf-8" -d '{"name": "admin", "password": "password"}' http://127.0.0.1:5984/_session

      ### MONGODB
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.12.0
        if: "endsWith(matrix.taskname, 'mongoid')"
        with:
          mongodb-version: "8.0"

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ruby & RubyGems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          rubygems: ${{ matrix.rubygems }}
          bundler: ${{ matrix.bundler }}
          bundler-cache: false
      # This will use the BUNDLE_GEMFILE set to matrix.gemfile (i.e. Appraisal.root)
      # We need to do this first to get appraisal installed.
      # NOTE: This does not use the root Gemfile at all.
      - name: Bundle for Appraisal ${{ matrix.appraisal }} (Rails v${{ matrix.rails}})
        run: bundle
      - name: Install Appraisal ${{ matrix.appraisal }} (Rails v${{ matrix.rails}}) dependencies
        run: bundle exec appraisal ${{ matrix.appraisal }} bundle
      - name: Run ${{ matrix.appraisal }} tests via ${{ matrix.taskname }} (Rails v${{ matrix.rails}})
        run: bundle exec appraisal ${{ matrix.appraisal }} bundle exec rake ${{ matrix.taskname }}
